version: "3.8"

services:
  redis:
    container_name: "redis"
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  zookeeper:
    container_name: "zookeeper"
    image: zookeeper:latest
    restart: always
    ports:
      - "2181:2181"

  kafka:
    container_name: "kafka"
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1